//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyBinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyBinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to == Combat ==
        ///GBA_Fire
        ///GBA_SwitchFireMode
        ///GBA_IronsightsToggle
        ///GBA_Reload
        ///GBA_Grenade
        ///GBA_NextWeapon
        ///GBA_PrevWeapon
        ///GBA_SwitchWeapon1
        ///GBA_SwitchWeapon2
        ///GBA_SwitchWeapon3
        ///GBA_SwitchWeapon4
        ///GBA_DropWeapon
        ///== Basic Controls ==
        ///GBA_MoveForward
        ///GBA_Backward
        ///GBA_StrafeLeft
        ///GBA_StrafeRight
        ///GBA_Sprint
        ///GBA_Jump
        ///GBA_Use
        ///GBA_QuickHeal
        ///GBA_CrouchToggle
        ///GBA_ToggleFlashlight
        ///GBA_TossMoney
        ///== Various ==
        ///GBA_ShowMenu
        ///GBA_Talk
        ///GBA_TeamTalk
        ///GBA_ShowScores
        ///GBA_VoiceChat.
        /// </summary>
        internal static string KillingFloor2Actions {
            get {
                return ResourceManager.GetString("KillingFloor2Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///B
        ///C
        ///D
        ///E
        ///F
        ///G
        ///H
        ///I
        ///J
        ///K
        ///L
        ///M
        ///N
        ///O
        ///P
        ///Q
        ///R
        ///S
        ///T
        ///U
        ///V
        ///W
        ///X
        ///Y
        ///Z
        ///one
        ///two
        ///three
        ///four
        ///LeftMouseButton
        ///MiddleMouseButton
        ///RightMouseButton
        ///Enter
        ///BackSpace
        ///LeftShift
        ///CapsLock.
        /// </summary>
        internal static string KillingFloor2PossibleKeys {
            get {
                return ResourceManager.GetString("KillingFloor2PossibleKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bindings=(Name=&quot;A&quot;,Command=,Control=False,Shift=False,Alt=False,bIgnoreCtrl=False,bIgnoreShift=False,bIgnoreAlt=False)
        ///Bindings=(Name=&quot;B&quot;,Command=,Control=False,Shift=False,Alt=False,bIgnoreCtrl=False,bIgnoreShift=False,bIgnoreAlt=False)
        ///Bindings=(Name=&quot;C&quot;,Command=,Control=False,Shift=False,Alt=False,bIgnoreCtrl=False,bIgnoreShift=False,bIgnoreAlt=False)
        ///Bindings=(Name=&quot;D&quot;,Command=,Control=False,Shift=False,Alt=False,bIgnoreCtrl=False,bIgnoreShift=False,bIgnoreAlt=False)
        ///Bindings=(Name=&quot;E&quot;,Command=,Cont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KillingFloor2PossibleKeysMap {
            get {
                return ResourceManager.GetString("KillingFloor2PossibleKeysMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Engine.PlayerInput]
        ///MoveForwardSpeed=1200
        ///MoveStrafeSpeed=1200
        ///LookRightScale=300
        ///LookUpScale=-250
        ///MouseSensitivity=30.000000
        ///DoubleClickTime=0.250000
        ///bEnableMouseSmoothing=true
        ///Bindings=(Name=&quot;Duck&quot;,Command=&quot;Button bDuck | Axis aUp Speed=-1.0  AbsoluteAxis=100&quot;)
        ///Bindings=(Name=&quot;Look&quot;,Command=&quot;Button bLook&quot;)
        ///Bindings=(Name=&quot;Pause&quot;,Command=&quot;Pause&quot;)
        ///Bindings=(Name=&quot;LookToggle&quot;,Command=&quot;Toggle bLook&quot;)
        ///Bindings=(Name=&quot;LookUp&quot;,Command=&quot;Axis aLookUp Speed=+25.0 AbsoluteAxis=100&quot;)
        ///Bindings=(Name=&quot;Loo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KillingFloor2Template {
            get {
                return ResourceManager.GetString("KillingFloor2Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to == Combat ==
        ///Fire
        ///AltFire
        ///ToggleAiming
        ///ReloadWeapon
        ///QuickHeal
        ///ThrowNade
        ///ThrowWeapon
        ///SwitchWeapon 1
        ///SwitchWeapon 2
        ///SwitchWeapon 3
        ///SwitchWeapon 4
        ///SwitchWeapon 5
        ///PrevWeapon
        ///NextWeapon
        ///== Basic Controls ==
        ///ShowScores
        ///Use
        ///TossCash
        ///MoveForward
        ///MoveBackward
        ///StrafeLeft
        ///StrafeRight
        ///ToggleDuck
        ///Jump
        ///ToggleFlashlight
        ///Walking
        ///LookDown
        ///== Communication ==
        ///Speak Team
        ///Speak Public
        ///Speak Local
        ///Talk
        ///VoiceTalk
        ///TeamTalk
        ///SpeechMenuToggle
        ///== Various ==
        ///ConsoleToggle
        ///ScoreToggle
        ///GrowHUD
        ///Shr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KillingFloorActions {
            get {
                return ResourceManager.GetString("KillingFloorActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Unassigned--
        ///0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///F1
        ///F2
        ///F3
        ///F4
        ///F5
        ///F6
        ///F7
        ///F8
        ///F9
        ///F10
        ///F11
        ///F12
        ///F13
        ///F14
        ///F15
        ///F16
        ///F17
        ///F18
        ///F19
        ///F20
        ///F21
        ///F22
        ///F23
        ///F24
        ///A
        ///B
        ///C
        ///D
        ///E
        ///F
        ///G
        ///H
        ///I
        ///J
        ///K
        ///L
        ///M
        ///N
        ///O
        ///P
        ///Q
        ///R
        ///S
        ///T
        ///U
        ///V
        ///W
        ///X
        ///Y
        ///Z
        ///ALT
        ///Attn
        ///Backslash
        ///Backspace
        ///Cancel
        ///CapsLock
        ///Comma
        ///CrSel
        ///Ctrl
        ///Delete
        ///Down
        ///End
        ///Enter
        ///Equals
        ///Escape
        ///ErEof
        ///Execute
        ///ExSel
        ///GreySlash
        ///GreyStar
        ///GreyMinus
        ///GreyPlus
        ///Help
        ///home
        ///Insert
        ///LControl
        ///Left
        ///LeftBracket
        ///LShift
        ///Minus
        ///NoName
        ///None
        ///OemClear
        ///PA1
        ///PageDo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KillingFloorPossibleKeys {
            get {
                return ResourceManager.GetString("KillingFloorPossibleKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DefaultPlayer]
        ///Name=KFPlayer
        ///Class=Engine.Pawn
        ///Character=Corporal_Lewis
        ///team=1
        ///Sex=M
        ///
        ///[Engine.Input]
        ///Aliases[0]=(Command=&quot;Button bFire | Fire&quot;,Alias=Fire)
        ///Aliases[1]=(Command=&quot;Button bAltFire | AltFire&quot;,Alias=AltFire)
        ///Aliases[2]=(Command=&quot;Axis aBaseY  Speed=+300.0&quot;,Alias=MoveForward)
        ///Aliases[3]=(Command=&quot;Axis aBaseY  Speed=-300.0&quot;,Alias=MoveBackward)
        ///Aliases[4]=(Command=&quot;Axis aBaseX Speed=-40.0&quot;,Alias=TurnLeft)
        ///Aliases[5]=(Command=&quot;Axis aBaseX  Speed=+40.0&quot;,Alias=TurnRight)
        ///Aliases[6]=(Comman [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KillingFloorTemplate {
            get {
                return ResourceManager.GetString("KillingFloorTemplate", resourceCulture);
            }
        }
    }
}
